### PR TITLE
Mark eclipse-collections immutable collections as collection-like for nested list handling [Fixes #71]

### LINKED ISSUE #71: [eclipse-collection] can not deserialize concrete class instance inside nested immutable eclipse-collection
Hi, the issue is like the following:  
I have a field like 

``` Java
@JsonProperty
  private ImmutableMap<String, ImmutableList<AbstractDownloaderConfigeration>> keyToItemsList;
```
where `AbstractDownloaderConfigeration` is declared as:
``` Java
@Getter
@AllArgsConstructor
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "_type")
@JsonSubTypes({
    @JsonSubTypes.Type(value = MetaYoutubeDlConfiguration .class, name = "type 1")
})
public abstract class AbstractDownloaderConfigeration{
   //some fields
}
```
and the `MetaYoutubeDlConfiguration ` class is:
``` Java
@Getter @ToString
@NoArgsConstructor(force = true, access = AccessLevel.PROTECTED)
public class MetaYoutubeDlConfiguration extends AbstractDownloaderConfigeration {
  //more fields
}
```
As you can see I have already properly set up the `@JsonTypeInfo` and `@JsonSubTypes` on the abstract class,  
but I still got:
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `mikufan.cx.vocadb_pv_downloader.config.downloader.AbstractDownloaderConfigeration` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (File); line: 9, column: 7] (through reference chain: mikufan.cx.vocadb_pv_downloader.config.entity.UserConfig["downloaderConfigs"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1615)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1077)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:265)
	at com.fasterxml.jackson.datatype.eclipsecollections.deser.BaseCollectionDeserializer$Ref.add(BaseCollectionDeserializer.java:318)
	at com.fasterxml.jackson.datatype.eclipsecollections.deser.BaseCollectionDeserializer$Ref.add(BaseCollectionDeserializer.java:268)
	at com.fasterxml.jackson.datatype.eclipsecollections.deser.BaseCollectionDeserializer._deserializeContents(BaseCollectionDeserializer.java:80)
	at com.fasterxml.jackson.datatype.eclipsecollections.deser.BaseCollectionDeserializer.deserialize(BaseCollectionDeserializer.java:66)
	at com.fasterxml.jackson.datatype.eclipsecollections.deser.map.RefValueHandler.value(RefValueHandler.java:60)
	at com.fasterxml.jackson.datatype.eclipsecollections.deser.map.TypeHandlerPair$1.add(TypeHandlerPair.java:188)
	at com.fasterxml.jackson.datatype.eclipsecollections.deser.map.TypeHandlerPair$1.add(TypeHandlerPair.java:166)
	at com.fasterxml.jackson.datatype.eclipsecollections.deser.map.EclipseMapDeserializers$Entry$DeserializerImpl.deserializeEntry(EclipseMapDeserializers.java:311)
	at com.fasterxml.jackson.datatype.eclipsecollections.deser.map.EclipseMapDeserializer.deserialize(EclipseMapDeserializer.java:83)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3299)
	at mikufan.cx.project_vd_common_util.io.JacksonPojoTransformer.read(JacksonPojoTransformer.java:50)
	at mikufan.cx.vocadb_pv_downloader.config.parser.ArgParser.lambda$getUserConfigOrThrow$4(ArgParser.java:125)
	at mikufan.cx.project_vd_common_util.exception.ThrowableFunction.lambda$toFunction$0(ThrowableFunction.java:23)
	at mikufan.cx.project_vd_common_util.cli.parser.ParserUtil.getOrElse(ParserUtil.java:47)
	at mikufan.cx.project_vd_common_util.cli.parser.ParserUtil.getValueOrElse(ParserUtil.java:25)
	at mikufan.cx.vocadb_pv_downloader.config.parser.ArgParser.getUserConfigOrThrow(ArgParser.java:137)
	at mikufan.cx.vocadb_pv_downloader.config.ConfigFactory.getConfig(ConfigFactory.java:35)
	at mikufan.cx.vocadb_pv_downloader.Main.main(Main.java:15)
```
However, if I change the type of `keyToItemsList` from `ImmutableMap<String, ImmutableList<AbstractDownloaderConfigeration>>` to `ImmutableMap<String, List<AbstractDownloaderConfigeration>>` (using java.util.List inside the eclipse collection map), everything works fine, even though I have used Lombok in my code
 
I think this is a bug in this Jackson module. So I reported here

### PR DESCRIPTION
**Pull request by yawkat**

### CODE REVIEW

File: eclipse-collections/src/main/java/com/fasterxml/jackson/datatype/eclipsecollections/EclipseCollectionsTypeModifier.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+import com.fasterxml.jackson.databind.type.TypeFactory;
+import com.fasterxml.jackson.databind.type.TypeModifier;
+import java.lang.reflect.Type;
+import org.eclipse.collections.api.collection.ImmutableCollection;
+
+class EclipseCollectionsTypeModifier extends TypeModifier {
+    @Override
+    public JavaType modifyType(JavaType type, Type jdkType, TypeBindings context, TypeFactory typeFactory) {
+        if (!type.isCollectionLikeType()) {
+            JavaType collectionType = type.findSuperType(ImmutableCollection.class);
```
Comment (yawkat) [inline eclipse-collections/src/main/java/com/fasterxml/jackson/datatype/eclipsecollections/EclipseCollectionsTypeModifier.java:15]: is this a hot enough path to justify an isAssignableFrom check or is this fine?

**Comment by yawkat** [comment]
ImmutableMap was not affected by this because it has a different code path. For Map deserializers we have a giant typextype table of deserializer handlers which have to fish the type parameter out of the JavaType directly because the position differs (eg IntObjectMap has the value type as parameter 0, while MutableMap has the value type as parameter 1). 

Could maybe make the same change for map-likes as well, but not sure what exact use case it would fix (maybe custom annotations on the property would work?). Also not sure how or if it would work with primitive->ref maps, since those technically don't have a key in the type param?

**Comment by yawkat** [comment]
Looking at it further, for map-like deser with proper value type deserializer support I'd like to stick to 2.12 because that's where the templated implementation was introduced. A lot less work in that branch :)

File: eclipse-collections/src/main/java/com/fasterxml/jackson/datatype/eclipsecollections/EclipseCollectionsDeserializers.java [hunk 2]
```diff
@@ -183,7 +198,18 @@
...
 
+    @Override
+    public JsonDeserializer<?> findMapLikeDeserializer(
+            MapLikeType type,
+            DeserializationConfig config,
+            BeanDescription beanDesc,
+            KeyDeserializer keyDeserializer,
+            TypeDeserializer elementTypeDeserializer,
+            JsonDeserializer<?> elementDeserializer
+    ) throws JsonMappingException {
```
Comment (cowtowncoder) [inline eclipse-collections/src/main/java/com/fasterxml/jackson/datatype/eclipsecollections/EclipseCollectionsDeserializers.java:212]: Delegation here loses some information about possible custom key and value deserializers, as well as type deserializers (needed for polymorphic handling of values). Method called can of course try to figure out these details on its own but that's quite a bit of work.

File: eclipse-collections/src/main/java/com/fasterxml/jackson/datatype/eclipsecollections/EclipseCollectionsTypeModifier.java (hunk 1 above)
Comment (cowtowncoder) [reply eclipse-collections/src/main/java/com/fasterxml/jackson/datatype/eclipsecollections/EclipseCollectionsTypeModifier.java:15]: Which check are you referring to? `isCollectionLikeType()` is cheap so I think that is fine.
And `findSuperType()` is necessary to find type parameterization.

Comment (cowtowncoder) [reply eclipse-collections/src/main/java/com/fasterxml/jackson/datatype/eclipsecollections/EclipseCollectionsTypeModifier.java:15]: Oh. Ah, now I get it; to see if `findSuperType()` is needed. Hmmh. Ideally it should not be on hot path... but I probably would have added guard statement just in case. Should be fine either way.

**Comment by cowtowncoder** [comment]
Yes, 2.12 is fine, I am hoping to get first release candidate out during September; and if bigger/riskier changes are needed it makes sense too.

The main benefit of making type `MapLike` is wrt support for standard annotations for denoting key/value (de)serializers, and value type (de)serializer (polymorphic values).
It's def bit of judgment call on primitive types and so on; it's fine to give nominal type of, say, `java.lang.Object` as placeholder, but then again at some point data type has so many exceptions that maybe type refinement makes no sense.

File: eclipse-collections/src/main/java/com/fasterxml/jackson/datatype/eclipsecollections/EclipseCollectionsDeserializers.java (hunk 2 above)
Comment (yawkat) [reply eclipse-collections/src/main/java/com/fasterxml/jackson/datatype/eclipsecollections/EclipseCollectionsDeserializers.java:212]: Since none of the Map types are actually reported as map-like at this point (and I don't wanna patch it into 2.11) it's a bit of a moot point. Right now the value type deser is determined directly from the JavaType like you say in RefValueHandler.java and EclipseMapDeserializers.java:274.

How about removing the addition of this maplike method from this PR since it's superfluous and I make a second PR against 2.12 for map-like?

Comment (cowtowncoder) [reply eclipse-collections/src/main/java/com/fasterxml/jackson/datatype/eclipsecollections/EclipseCollectionsDeserializers.java:212]: I trust you to know this well enough so no objections.

**Comment by cowtowncoder** [comment]
Also: feel free to merge; I'm happy to do that but it is usually safer for module author to do it just in case there was some small piece missing.

**Comment by yawkat** [comment]
@cowtowncoder I don't have access to merge here

**Comment by cowtowncoder** [comment]
@yawkat Oops. That is an oversight -- I invited you to team that should have access. Please let me know if it does not work.
As I said, I don't mind merging but also do not want to be a blocker when my response times sometimes vary.

**Comment by yawkat** [comment]
@cowtowncoder I'm in the org now but can't merge this PR still.

Also, if I do the merging, I assume I should also port the patch to other versions (2.12, master), what's your workflow for this? Just cherry pick + run the tests?

**Comment by cowtowncoder** [comment]
Merging should simply work from older to newer as I do not cherry-pick in those cases. Cherry-picking needed for occasional reverse case (in which I add change in master, then cherry-pick into oldest, then forward [if there are intervening versions]).

I'll merge this, will see why you don't have access.

**Comment by cowtowncoder** [comment]
Looks like there is one failing test case, due to minor flaw in `CollectionLikeType` / `MapLikeType` handling: there are matching `isTrueCollectionType()` / `isTrueMapType()` methods that check contained type (is underlying erased type `Collection` or `Map`) -- which might be ok, except that then caller assumes what follows is that one can upcast to `MapType` / `CollectionType`. Normally that is fine but looks like here sometimes real `Collection` is only promoted as `CollectionLikeType` causing exception with `BasicSerializerFactory`.

I will patch code in jackson-databind for 2.11.3 (and further in 2.12), although not sure if there might be improvement to be made in TypeModifier for eclipse-collections: if it knows type is `Collection`, it should promote to `CollectionType`.
But I don't know if this is known in type hierarchy -- either way, I can work around this issue.

**Comment by cowtowncoder** [comment]
Ok. There seems to be some issue left as `SerializerTest#ref()` now fails with:

```
com.fasterxml.jackson.databind.JsonMappingException: Size must be 1 but was 3 (through reference chain: org.eclipse.collections.impl.set.immutable.ImmutableTripletonSet["only"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:763)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4406)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3660)
	at com.fasterxml.jackson.datatype.eclipsecollections.SerializerTest.ref(SerializerTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.IllegalStateException: Size must be 1 but was 3
	at org.eclipse.collections.impl.set.immutable.ImmutableTripletonSet.getOnly(ImmutableTripletonSet.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
	... 29 more


```

**Comment by cowtowncoder** [comment]
Merged from 2.11 -> 2.12 -> master, same test fail in all (which probably makes sense).

**Comment by cowtowncoder** [comment]
On team: for some reason it only had "read" access (about same as all devs); changed it to give push access so merging should now be accessible.

**Comment by yawkat** [comment]
#73
